### ISSUE TITLE
Datagridxl2 event "setcellvalues" did not work.

### ISSUE THREAD

**Issue by MinatoHokage4th** [DataGridXL/DataGridXL2#118]
Dear DataGridXL2 Maintainer and Developer,

**Bug Report : Datagridxl2 event '[setcellvalues](https://v2.datagridxl.com/api/events#actions:cell)' not working**
I was trying to set a custom event, when a cell on {x,y} was changed / set a value then i want other cells on same row was modify with default value.
I was try to set the event, but sometime return an error like **"Uncaught InternalError: too much recursion"**.
It seem this library need show more example by solve basic use case (like this issue).

Could you please help me? Thank You.

Here i place my custom event
```
var setter = function(){
    let x1 = newgrid.getCellCursorPosition().x;
    let y1 = newgrid.getCellCursorPosition().y;
    console.log('x1 : '+x1+'y1 : '+y1);
    if(x1 == 0){
        console.log('0');
        newgrid.setCellValues({x:2,y:y1}, "Default");
        newgrid.setCellValues({x:9,y:y1}, "0");
    }
};
newgrid.events.on('setcellvalues', setter);
newgrid.events.off('setcellvalues', setter);
```

Here Full my html file : 
[local_test_datagridxl2.txt](https://github.com/user-attachments/files/16430229/local_test_datagridxl2.txt)

Extra : Beside that, can you give me any advice how to make cells on specific columns has a data validation (or simply dropdown) to make better experience if allowed value type like an `enum("MALE","FEMALE")`. I am still confused how to make it work.

_Sincerely,_
Minato

**Comment by DataGridXL** [comment]
Hi Minato,

To use DataGridXL in live environments, a commercial license is required. You can purchase such license here: https://datagridxl.com/pricing.

We will then gladly provide you with the technical support to solve any code related issue you may encounter.

Thanks.
Robbert
