### ISSUE TITLE
Error: Could not find a declaration file for module

### ISSUE THREAD

**Issue by ayush1852017** [DataGridXL/DataGridXL2#38]
![Screenshot from 2022-09-23 11-23-03](https://user-images.githubusercontent.com/46336517/191899581-181bfee5-e3a8-4159-970b-bf03ce3c74bf.png)

I am getting this error while importing `import DataGridXL from '@datagridxl/datagridxl2';`
Is there any way to use this in Angular. 

Also, It would be helpful, If anyone has Angular implementation code for latest version.

Thanks

**Comment by DataGridXL** [comment]
Terribly sorry for the late reply! I think we have sent you a reply on our helpdesk, in which we refer to [this article](https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3) that explains how to build a `d.ts` file for a vanilla JS component.

We're getting more TypeScript users now, asking the same question, and we will soon include a declarations file (`d.ts`) in the project itself, so you won't have to do that manually.
