### ISSUE TITLE
copy to clipboard with headers

### ISSUE THREAD

**Issue by achillis2** [DataGridXL/DataGridXL2#39]
The upper left square in the table can be clicked to highlight all and copy, but it doesn't include the headers. What option should we set to include the headers, not just the data rows? Thanks

**Comment by DataGridXL** [comment]
I believe we have already replied to your question on our main support channel, but here's the answer anyway:

Copying a selection of cells never copies the (column) headers. DGXL does not have a built-in option to copy the headers along with the cells (you can use `grid.getData()` for that).
 
One suggestion I have is to make your column headers part of the grid. I have created a Codepen demo to show you what I mean: https://codepen.io/datagridxl/pen/vYrGqBY.
```
var data = [
  ['header 1', 'header 2', 'header 3'],
  [1,2,3],
  [4,5,6]
];
```
 
Even if the headers are part of the editable cells, you can cancel any changes to the header cells. This way headers are copied, but not editable.
 
Please have a look at the Codepen demo to see how it's done.
