### ISSUE TITLE
Add catch-all event "change" 

### ISSUE THREAD

**Issue by DataGridXL** [DataGridXL/DataGridXL2#4]
It's already on our API page: 

_Catch-all event for any event that might change the data set: setcellvalues, deletecols/-rows, insertcols/-rows, movecols/-rows._

**Comment by seanho96** [comment]
The catch-all event 'change' doesn't seem to be working even on the [demo](https://www.datagridxl.com/api/events) page.

**Comment by DataGridXL** [comment]
Added in latest update v2.23.03.02
