### ISSUE TITLE
Fix setcellcursorposition event

### ISSUE THREAD

**Issue by DataGridXL** [DataGridXL/DataGridXL2#48]
setcellcursorposition event does not fire

**Comment by dj-kefir-siorbacz** [comment]
Hi @DataGridXL !

I wanted to store the coordinates of the last selected cell. 
Is it somehow possible right now?

Also, what's the code for listening for events? 

```
grid.events.on("setcellcursorposition", (e) => {
    [...]
});
```
Something like this?

**Comment by DataGridXL** [comment]
Hi @dj-kefir-siorbacz 

Sorry for the late reply! Yes, listen to events like so:

```
var lastSelectedCell = null;
grid.events.on('setselection', function(gridEvent){
  lastSelectedCell = gridEvent.cellCursorPosition;
});
```

Hope this helps!

**Comment by DataGridXL** [comment]
Will be fixed in v3. For v2, devs can listen to `setselection` event.
