### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dj-kefir-siorbacz** [DataGridXL/DataGridXL2#49]
I got `Uncaught RangeError: Maximum call stack size exceeded` when running:

```
new DataGridXL("grid", {
                        data: DataGridXL.createDummyData(500000, 1),
                        allowInsertRows: false,
                        allowDeleteRows: false,
                        allowMoveRows: false,
                        allowInsertCols: false,
                        allowDeleteCols: false,
                        allowMoveCols: false,
                        allowFillCells: false,
                        allowEditCells: false,
                        allowCut: false,
                        allowPaste: false,
                        allowResizeCols: true,
                        allowCopy: true
                    });
```

It seems like you can't achieve 1 million cells with super thin and long columns :( 

Does DataGridXL have something that would allow me to split my data and have it loaded whenever the user scrolls down/up far enough to trigger loading the new pagination. And then comes another question: would I need to instantiate a new table or is there some method/function for appending data to the table?

**Comment by DataGridXL** [comment]
Hi,

This is a known issue for grids with (too) many records. What is too many records? It likely depends on a combination of the browser + OS + perhaps system hardware so it's impossible to say.

We generally advice a row limit of 10,000, then use custom built pagination buttons that replace the grid instance with a new one with the data for the other page.

Something like this:

```
grid.destroy();
grid = new DataGridXL("grid", {
  data: data_for_page_2
});
``` 

We will think of a method to support more records in a single DGXL instance, but we don't have an exact plan for it yet.

**Comment by dj-kefir-siorbacz** [comment]
Thanks! That clears things up :)
