### ISSUE TITLE
getCellValue always returns undefined

### ISSUE THREAD

**Issue by dj-kefir-siorbacz** [DataGridXL/DataGridXL2#50]
Hi @DataGridXL !

I can't get a value from a cell. I'm trying to use `getCellValue`, but it always returns `undefined`.
How should I call this function? With two coordiantes arguments? With 1 dict arguemnt? or with array?

**Comment by DataGridXL** [comment]
Hi,

Cell coordinates are written {x,y}. To get the value from the very first cell, write:

grid.getCellValue({x:0,y:0})

Hope this helps!
