### ISSUE TITLE
Custom cell editors

### ISSUE THREAD

**Issue by jperon** [DataGridXL/DataGridXL2#51]
Hello,

First let me thank you for this very good piece of software!
Seeing https://github.com/DataGridXL/DataGridXL/issues/8 closed, I was wondering whether it was possible to define custom editors, especially autocomplete and date picker. I didn’t find anything about it in documentation.
Thank you again!

**Comment by DataGridXL** [comment]
Hi,

Thank you! Custom cell editors will be part of version 3 to be released
march 2024.

Hope this helps!

Op do 19 okt. 2023 22:49 schreef jperon ***@***.***>:

**Comment by jperon** [comment]
It does, really. If you’d like beta testers, feel free to ask!

**Comment by DataGridXL** [comment]
Best way to get notified for our v3 Beta program is to subscribe to the email list, here's the link: http://eepurl.com/hvAJbv.

Thanks!
